name: rpg_character_generator_new
description: Générateur de personnages et PNJ pour jeux de rôle INS/MV
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  intl: ^0.19.0
  uuid: ^4.5.1
  path: ^1.9.0
  file_picker: ^8.1.4
  share_plus: ^10.1.2
  cross_file: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
